name: flutter_weather_icons
description: Flutter package for Weather Icons. Weather Icons is a pack of 222 beautifully crafted Open Source icons for representing weather and climate
version: 2.0.0
author: Rishi Banerjee <rishieric91@gmail.com> - Updated for newer flutter versions by Chris Scutt
homepage: https://github.com/rshrc/flutter_weather_icons

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  recase:

flutter:
  fonts:
    - family: WeatherIcons
      fonts:
        - asset: fonts/weathericons.ttf
