name: flutter_weather_conditions
description: Flutter package for Weather Icons. Weather Icons is a pack of 222 beautifully crafted Open Source icons for representing weather and climate
version: 1.0.1
author: Mark Jackson <dromosys@gmail.com> - forked from Scuttman/flutter_weather_conditions
homepage: https://github.com/dromosys/flutter_weather_conditions

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  recase:

flutter:
  fonts:
    - family: WeatherIcons
      fonts:
        - asset: fonts/weathericons.ttf
